version: '3.7'

services:
    api:
        build: 
            context: ./app
            dockerfile: Dockerfile.prod
        command: gunicorn api.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - static_volume:/home/app/api/staticfiles
        expose:
            - 8000
        env_file:
            - ./.env.prod
        depends_on:
            - db
    nginx:
        build: ./nginx
        volumes:
            - static_volume:/home/app/api/staticfiles
        ports:
            - 1337:80
        depends_on:
            - api
    db:
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./.env.prod.db
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin-prod
        depends_on:
            - db
        ports:
            - 5051:80
        env_file:
            - ./.env.prod.pgadmin
        restart: always 

    worker:
        build: ./app
        restart: 'no'
        env_file:
            - ./.env.prod.rabbitmq
        command: celery worker --app=api.celery --concurrency=1 --loglevel=INFO
        volumes:
            - ./app/:/usr/src/app/
        depends_on:
            - broker
    flower:
        image: zoomeranalytics/flower:0.9.1-4.0.2
        restart: 'no'
        env_file:
            - ./.env.prod.rabbitmq
        ports:
            - 5555:5555
        depends_on:
            - broker
    broker:
        image: rabbitmq:3
        env_file:
            - ./.env.prod.rabbitmq
        ports:
            - 5672:5672

volumes:
    postgres_data:
    static_volume:
